### ISSUE TITLE
Error when receiving Bnet whispers

### ISSUE THREAD

**Issue by 1701NCC** [Tercioo/RaidAssist#5]
Whenever i get whispered by anyone on my bnet friends list i get this error message. 

20x RaidAssist\plugins\invite-Invite.lua:158: attempt to call global 'BNGetFriendInfo' (a nil value)
[string "@RaidAssist\plugins\invite-Invite.lua"]:158: in function `?'
[string "@Ailo\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Ailo\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ailo\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Ailo\Libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...rfaceAilo\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Tercioo** [comment]
fixed

------ Original Message ------

**Comment by MDoom81** [comment]
This is still an issue for me, its not just bnet whispers, its any whisper. Version 9.0.2.184

**Comment by Tercioo** [comment]
going to look into this tomorrow


------ Original Message ------
